#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 18, 2025 09:43:15 PM EEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

_debug = True


_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class ReviewScreen:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("680x673+485+84")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.reviewscreenframe = tk.Frame(self.top)
        self.reviewscreenframe.place(relx=0.018, rely=0.022, relheight=0.964
                , relwidth=0.957)
        self.reviewscreenframe.configure(relief='groove')
        self.reviewscreenframe.configure(borderwidth="2")
        self.reviewscreenframe.configure(relief="groove")
        self.reviewscreenframe.configure(background="#c0c0c0")
        self.reviewscreenframe.configure(highlightbackground="#d9d9d9")
        self.reviewscreenframe.configure(highlightcolor="#000000")

        self.star2 = tk.Button(self.reviewscreenframe)
        self.star2.place(relx=0.382, rely=0.368, height=26, width=37)
        self.star2.configure(activebackground="#d9d9d9")
        self.star2.configure(activeforeground="black")
        self.star2.configure(background="#d9d9d9")
        self.star2.configure(disabledforeground="#a3a3a3")
        self.star2.configure(font="-family {Segoe UI} -size 9")
        self.star2.configure(foreground="#000000")
        self.star2.configure(highlightbackground="#d9d9d9")
        self.star2.configure(highlightcolor="#000000")
        self.star2.configure(text='★')

        self.star3 = tk.Button(self.reviewscreenframe)
        self.star3.place(relx=0.47, rely=0.368, height=26, width=37)
        self.star3.configure(activebackground="#d9d9d9")
        self.star3.configure(activeforeground="black")
        self.star3.configure(background="#d9d9d9")
        self.star3.configure(disabledforeground="#a3a3a3")
        self.star3.configure(font="-family {Segoe UI} -size 9")
        self.star3.configure(foreground="#000000")
        self.star3.configure(highlightbackground="#d9d9d9")
        self.star3.configure(highlightcolor="#000000")
        self.star3.configure(text='★')

        self.star4 = tk.Button(self.reviewscreenframe)
        self.star4.place(relx=0.558, rely=0.368, height=26, width=37)
        self.star4.configure(activebackground="#d9d9d9")
        self.star4.configure(activeforeground="black")
        self.star4.configure(background="#d9d9d9")
        self.star4.configure(disabledforeground="#a3a3a3")
        self.star4.configure(font="-family {Segoe UI} -size 9")
        self.star4.configure(foreground="#000000")
        self.star4.configure(highlightbackground="#d9d9d9")
        self.star4.configure(highlightcolor="#000000")
        self.star4.configure(text='★')

        self.star5 = tk.Button(self.reviewscreenframe)
        self.star5.place(relx=0.644, rely=0.368, height=26, width=37)
        self.star5.configure(activebackground="#d9d9d9")
        self.star5.configure(activeforeground="black")
        self.star5.configure(background="#d9d9d9")
        self.star5.configure(disabledforeground="#a3a3a3")
        self.star5.configure(font="-family {Segoe UI} -size 9")
        self.star5.configure(foreground="#000000")
        self.star5.configure(highlightbackground="#d9d9d9")
        self.star5.configure(highlightcolor="#000000")
        self.star5.configure(text='★')

        self.Aboutmeframe = tk.Label(self.reviewscreenframe)
        self.Aboutmeframe.place(relx=0.349, rely=0.461, height=31, width=185)
        self.Aboutmeframe.configure(activebackground="#d9d9d9")
        self.Aboutmeframe.configure(activeforeground="black")
        self.Aboutmeframe.configure(anchor='w')
        self.Aboutmeframe.configure(background="#c0c0c0")
        self.Aboutmeframe.configure(compound='left')
        self.Aboutmeframe.configure(disabledforeground="#a3a3a3")
        self.Aboutmeframe.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Aboutmeframe.configure(foreground="#000000")
        self.Aboutmeframe.configure(highlightbackground="#d9d9d9")
        self.Aboutmeframe.configure(highlightcolor="#000000")
        self.Aboutmeframe.configure(text='''About me''')

        self.reviews = tk.Label(self.reviewscreenframe)
        self.reviews.place(relx=0.452, rely=0.667, height=31, width=61)
        self.reviews.configure(activebackground="#d9d9d9")
        self.reviews.configure(activeforeground="black")
        self.reviews.configure(anchor='w')
        self.reviews.configure(background="#d9d9d9")
        self.reviews.configure(compound='left')
        self.reviews.configure(disabledforeground="#a3a3a3")
        self.reviews.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.reviews.configure(foreground="#000000")
        self.reviews.configure(highlightbackground="#d9d9d9")
        self.reviews.configure(highlightcolor="#000000")
        self.reviews.configure(text='''Reviews''')

        self.addreviewbutton = tk.Button(self.reviewscreenframe)
        self.addreviewbutton.place(relx=0.765, rely=0.804, height=26, width=87)
        self.addreviewbutton.configure(activebackground="#d9d9d9")
        self.addreviewbutton.configure(activeforeground="black")
        self.addreviewbutton.configure(background="#0080c0")
        self.addreviewbutton.configure(disabledforeground="#a3a3a3")
        self.addreviewbutton.configure(font="-family {Segoe UI} -size 9")
        self.addreviewbutton.configure(foreground="#ffffff")
        self.addreviewbutton.configure(highlightbackground="#d9d9d9")
        self.addreviewbutton.configure(highlightcolor="#000000")
        self.addreviewbutton.configure(text='''Add Review''')

        self.reviewlist = tk.Listbox(self.reviewscreenframe)
        self.reviewlist.place(relx=0.416, rely=0.76, relheight=0.211
                , relwidth=0.181)
        self.reviewlist.configure(background="white")
        self.reviewlist.configure(disabledforeground="#a3a3a3")
        self.reviewlist.configure(font="TkFixedFont")
        self.reviewlist.configure(foreground="#000000")
        self.reviewlist.configure(highlightbackground="#d9d9d9")
        self.reviewlist.configure(highlightcolor="#000000")
        self.reviewlist.configure(selectbackground="#d9d9d9")
        self.reviewlist.configure(selectforeground="black")

        self.username = tk.Label(self.reviewscreenframe)
        self.username.place(relx=0.399, rely=0.299, height=34, width=112)
        self.username.configure(activebackground="#d9d9d9")
        self.username.configure(activeforeground="black")
        self.username.configure(anchor='w')
        self.username.configure(background="#ffffff")
        self.username.configure(compound='left')
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="-family {Segoe UI} -size 9")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="#000000")
        self.username.configure(text='''username''')

        self.aboutme = tk.Label(self.reviewscreenframe)
        self.aboutme.place(relx=0.349, rely=0.505, height=91, width=185)
        self.aboutme.configure(activebackground="#d9d9d9")
        self.aboutme.configure(activeforeground="black")
        self.aboutme.configure(anchor='w')
        self.aboutme.configure(background="#ffffff")
        self.aboutme.configure(compound='left')
        self.aboutme.configure(disabledforeground="#a3a3a3")
        self.aboutme.configure(font="-family {Segoe UI} -size 9")
        self.aboutme.configure(foreground="#000000")
        self.aboutme.configure(highlightbackground="#d9d9d9")
        self.aboutme.configure(highlightcolor="#ffffff")

        self.star1 = tk.Button(self.reviewscreenframe)
        self.star1.place(relx=0.296, rely=0.368, height=26, width=37)
        self.star1.configure(activebackground="#d9d9d9")
        self.star1.configure(activeforeground="black")
        self.star1.configure(background="#d9d9d9")
        self.star1.configure(disabledforeground="#a3a3a3")
        self.star1.configure(font="-family {Segoe UI} -size 9")
        self.star1.configure(foreground="#000000")
        self.star1.configure(highlightbackground="#d9d9d9")
        self.star1.configure(highlightcolor="#000000")
        self.star1.configure(text='★')

        self.UserPhoto = tk.Label(self.reviewscreenframe)
        self.UserPhoto.place(relx=0.399, rely=0.025, height=161, width=112)
        self.UserPhoto.configure(activebackground="#d9d9d9")
        self.UserPhoto.configure(activeforeground="black")
        self.UserPhoto.configure(anchor='w')
        self.UserPhoto.configure(background="#8080ff")
        self.UserPhoto.configure(compound='left')
        self.UserPhoto.configure(disabledforeground="#a3a3a3")
        self.UserPhoto.configure(font="-family {Segoe UI} -size 9")
        self.UserPhoto.configure(foreground="#000000")
        self.UserPhoto.configure(highlightbackground="#d9d9d9")
        self.UserPhoto.configure(highlightcolor="#000000")
        self.UserPhoto.configure(text='''userphoto''')


if __name__ == '__main__':
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    # _w1 = review.Toplevel1(_top1)
    _w1 = ReviewScreen(_top1)
    root.mainloop()