import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import DBManager
import MessageScreen
import MainMenuScreen
import PaymentScreen

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class eshopScreen:
        def __init__(self, top=None, root=None, username=None):
                self.username = username
                self.root = root
                self.top = top

                self.top.geometry("600x450+468+138")
                self.top.minsize(120, 1)
                self.top.maxsize(1540, 845)
                self.top.resizable(1,  1)
                self.top.title("Petato")
                self.top.configure(background="#d9d9d9")
                self.top.configure(highlightbackground="#d9d9d9")
                self.top.configure(highlightcolor="#000000")

                self.cart = []

                self.eshopframe = tk.Frame(self.top)
                self.eshopframe.place(relx=0.033, rely=0.022, relheight=0.944
                                , relwidth=0.942)
                self.eshopframe.configure(relief='groove')
                self.eshopframe.configure(borderwidth="2")
                self.eshopframe.configure(relief="groove")
                self.eshopframe.configure(background="#d9d9d9")
                self.eshopframe.configure(highlightbackground="#d9d9d9")
                self.eshopframe.configure(highlightcolor="#000000")

                self.item4frame = tk.Frame(self.eshopframe)
                self.item4frame.place(relx=0.035, rely=0.409, relheight=0.278
                                , relwidth=0.28)
                self.item4frame.configure(relief='groove')
                self.item4frame.configure(borderwidth="2")
                self.item4frame.configure(relief="groove")
                self.item4frame.configure(background="#d9d9d9")
                self.item4frame.configure(highlightbackground="#d9d9d9")
                self.item4frame.configure(highlightcolor="#000000")

                self.item4 = tk.Label(self.item4frame)
                self.item4.place(relx=0.063, rely=0.085, height=21, width=94)
                self.item4.configure(activebackground="#d9d9d9")
                self.item4.configure(activeforeground="black")
                self.item4.configure(anchor='w')
                self.item4.configure(background="#ffffff")
                self.item4.configure(compound='left')
                self.item4.configure(disabledforeground="#a3a3a3")
                self.item4.configure(foreground="#000000")
                self.item4.configure(highlightbackground="#d9d9d9")
                self.item4.configure(highlightcolor="#000000")
                self.item4.configure(text='''Item 4''')

                self.item4photo = tk.Label(self.item4frame)
                self.item4photo.place(relx=0.063, rely=0.339, height=41, width=114)
                self.item4photo.configure(activebackground="#d9d9d9")
                self.item4photo.configure(activeforeground="black")
                self.item4photo.configure(anchor='w')
                self.item4photo.configure(background="#ffffff")
                self.item4photo.configure(compound='left')
                self.item4photo.configure(disabledforeground="#a3a3a3")
                self.item4photo.configure(foreground="#000000")
                self.item4photo.configure(highlightbackground="#d9d9d9")
                self.item4photo.configure(highlightcolor="#000000")
                self.item4photo.configure(text='''item 4 photo''')

                self.addbutton4 = tk.Button(self.item4frame)
                self.addbutton4.place(relx=0.696, rely=0.085, height=26, width=37)
                self.addbutton4.configure(activebackground="#d9d9d9")
                self.addbutton4.configure(activeforeground="black")
                self.addbutton4.configure(background="#0000ff")
                self.addbutton4.configure(disabledforeground="#a3a3a3")
                self.addbutton4.configure(foreground="#ffffff")
                self.addbutton4.configure(highlightbackground="#d9d9d9")
                self.addbutton4.configure(highlightcolor="#000000")
                self.addbutton4.configure(text='''add''')
                self.addbutton4.configure(command=lambda: self.add_item(self.item4))


                self.learnmorebutton4 = tk.Button(self.item4frame)
                self.learnmorebutton4.place(relx=0.063, rely=0.763, height=26, width=137)

                self.learnmorebutton4.configure(activebackground="#d9d9d9")
                self.learnmorebutton4.configure(activeforeground="black")
                self.learnmorebutton4.configure(background="#d9d9d9")
                self.learnmorebutton4.configure(disabledforeground="#a3a3a3")
                self.learnmorebutton4.configure(foreground="#000000")
                self.learnmorebutton4.configure(highlightbackground="#d9d9d9")
                self.learnmorebutton4.configure(highlightcolor="#000000")
                self.learnmorebutton4.configure(text='''Learn more ->''')

                self.item5frame = tk.Frame(self.eshopframe)
                self.item5frame.place(relx=0.359, rely=0.409, relheight=0.278
                                , relwidth=0.28)
                self.item5frame.configure(relief='groove')
                self.item5frame.configure(borderwidth="2")
                self.item5frame.configure(relief="groove")
                self.item5frame.configure(background="#d9d9d9")
                self.item5frame.configure(highlightbackground="#d9d9d9")
                self.item5frame.configure(highlightcolor="#000000")

                self.item5 = tk.Label(self.item5frame)
                self.item5.place(relx=0.063, rely=0.085, height=21, width=94)
                self.item5.configure(activebackground="#d9d9d9")
                self.item5.configure(activeforeground="black")
                self.item5.configure(anchor='w')
                self.item5.configure(background="#ffffff")
                self.item5.configure(compound='left')
                self.item5.configure(disabledforeground="#a3a3a3")
                self.item5.configure(foreground="#000000")
                self.item5.configure(highlightbackground="#d9d9d9")
                self.item5.configure(highlightcolor="#000000")
                self.item5.configure(text='''Item 5''')

                self.item5photo = tk.Label(self.item5frame)
                self.item5photo.place(relx=0.063, rely=0.339, height=41, width=114)
                self.item5photo.configure(activebackground="#d9d9d9")
                self.item5photo.configure(activeforeground="black")
                self.item5photo.configure(anchor='w')
                self.item5photo.configure(background="#ffffff")
                self.item5photo.configure(compound='left')
                self.item5photo.configure(disabledforeground="#a3a3a3")
                self.item5photo.configure(foreground="#000000")
                self.item5photo.configure(highlightbackground="#d9d9d9")
                self.item5photo.configure(highlightcolor="#000000")
                self.item5photo.configure(text='''item 5 photo''')

                self.learnmore5 = tk.Button(self.item5frame)
                self.learnmore5.place(relx=0.063, rely=0.763, height=26, width=137)
                self.learnmore5.configure(activebackground="#d9d9d9")
                self.learnmore5.configure(activeforeground="black")
                self.learnmore5.configure(background="#d9d9d9")
                self.learnmore5.configure(disabledforeground="#a3a3a3")
                self.learnmore5.configure(foreground="#000000")
                self.learnmore5.configure(highlightbackground="#d9d9d9")
                self.learnmore5.configure(highlightcolor="#000000")
                self.learnmore5.configure(text='''Learn more ->''')

                self.addbutton5 = tk.Button(self.item5frame)
                self.addbutton5.place(relx=0.696, rely=0.085, height=26, width=37)
                self.addbutton5.configure(activebackground="#d9d9d9")
                self.addbutton5.configure(activeforeground="black")
                self.addbutton5.configure(background="#0000ff")
                self.addbutton5.configure(disabledforeground="#a3a3a3")
                self.addbutton5.configure(foreground="#ffffff")
                self.addbutton5.configure(highlightbackground="#d9d9d9")
                self.addbutton5.configure(highlightcolor="#000000")
                self.addbutton5.configure(text='''add''')
                self.addbutton5.configure(command=lambda: self.add_item(self.item5))


                self.Button1 = tk.Button(self.eshopframe)
                self.Button1.place(relx=0.396, rely=0.729, height=26, width=27)
                self.Button1.configure(activebackground="#d9d9d9")
                self.Button1.configure(activeforeground="black")
                self.Button1.configure(background="#0000ff")
                self.Button1.configure(disabledforeground="#a3a3a3")
                self.Button1.configure(foreground="#ffffff")
                self.Button1.configure(highlightbackground="#d9d9d9")
                self.Button1.configure(highlightcolor="#000000")
                self.Button1.configure(text='''1''')

                self.Button2 = tk.Button(self.eshopframe)
                self.Button2.place(relx=0.467, rely=0.729, height=26, width=27)
                self.Button2.configure(activebackground="#d9d9d9")
                self.Button2.configure(activeforeground="black")
                self.Button2.configure(background="#0000ff")
                self.Button2.configure(disabledforeground="#a3a3a3")
                self.Button2.configure(foreground="#ffffff")
                self.Button2.configure(highlightbackground="#d9d9d9")
                self.Button2.configure(highlightcolor="#000000")
                self.Button2.configure(text='''2''')

                self.Button3 = tk.Button(self.eshopframe)
                self.Button3.place(relx=0.542, rely=0.729, height=26, width=27)
                self.Button3.configure(activebackground="#d9d9d9")
                self.Button3.configure(activeforeground="black")
                self.Button3.configure(background="#0000ff")
                self.Button3.configure(disabledforeground="#a3a3a3")
                self.Button3.configure(foreground="#ffffff")
                self.Button3.configure(highlightbackground="#d9d9d9")
                self.Button3.configure(highlightcolor="#000000")
                self.Button3.configure(text='''3''')

                self.Buttonnext = tk.Button(self.eshopframe)
                self.Buttonnext.place(relx=0.612, rely=0.729, height=26, width=17)
                self.Buttonnext.configure(activebackground="#d9d9d9")
                self.Buttonnext.configure(activeforeground="black")
                self.Buttonnext.configure(background="#0000ff")
                self.Buttonnext.configure(disabledforeground="#a3a3a3")
                self.Buttonnext.configure(foreground="#ffffff")
                self.Buttonnext.configure(highlightbackground="#d9d9d9")
                self.Buttonnext.configure(highlightcolor="#000000")
                self.Buttonnext.configure(text='''>''')

                self.Buttonprevious = tk.Button(self.eshopframe)
                self.Buttonprevious.place(relx=0.342, rely=0.729, height=26, width=17)
                self.Buttonprevious.configure(activebackground="#d9d9d9")
                self.Buttonprevious.configure(activeforeground="black")
                self.Buttonprevious.configure(background="#0000ff")
                self.Buttonprevious.configure(disabledforeground="#a3a3a3")
                self.Buttonprevious.configure(foreground="#ffffff")
                self.Buttonprevious.configure(highlightbackground="#d9d9d9")
                self.Buttonprevious.configure(highlightcolor="#000000")
                self.Buttonprevious.configure(text='''<''')

                self.item1frame = tk.Frame(self.eshopframe)
                self.item1frame.place(relx=0.035, rely=0.047, relheight=0.278
                                , relwidth=0.28)
                self.item1frame.configure(relief='groove')
                self.item1frame.configure(borderwidth="2")
                self.item1frame.configure(relief="groove")
                self.item1frame.configure(background="#d9d9d9")
                self.item1frame.configure(highlightbackground="#d9d9d9")
                self.item1frame.configure(highlightcolor="#000000")

                self.learnmore1 = tk.Button(self.item1frame)
                self.learnmore1.place(relx=0.063, rely=0.763, height=26, width=137)
                self.learnmore1.configure(activebackground="#d9d9d9")
                self.learnmore1.configure(activeforeground="black")
                self.learnmore1.configure(background="#d9d9d9")
                self.learnmore1.configure(disabledforeground="#a3a3a3")
                self.learnmore1.configure(foreground="#000000")
                self.learnmore1.configure(highlightbackground="#d9d9d9")
                self.learnmore1.configure(highlightcolor="#000000")
                self.learnmore1.configure(text='''Learn more ->''')

                self.addbutton1 = tk.Button(self.item1frame)
                self.addbutton1.place(relx=0.633, rely=0.085, height=26, width=47)
                self.addbutton1.configure(activebackground="#d9d9d9")
                self.addbutton1.configure(activeforeground="black")
                self.addbutton1.configure(background="#0000ff")
                self.addbutton1.configure(disabledforeground="#a3a3a3")
                self.addbutton1.configure(foreground="#ffffff")
                self.addbutton1.configure(highlightbackground="#d9d9d9")
                self.addbutton1.configure(highlightcolor="#000000")
                self.addbutton1.configure(text='''add''')
                self.addbutton1.configure(command=lambda: self.add_item(self.item1))

                self.item1 = tk.Label(self.item1frame)
                self.item1.place(relx=0.063, rely=0.085, height=21, width=86)
                self.item1.configure(activebackground="#d9d9d9")
                self.item1.configure(activeforeground="black")
                self.item1.configure(anchor='w')
                self.item1.configure(background="#ffffff")
                self.item1.configure(compound='left')
                self.item1.configure(disabledforeground="#a3a3a3")
                self.item1.configure(foreground="#000000")
                self.item1.configure(highlightbackground="#d9d9d9")
                self.item1.configure(highlightcolor="#000000")
                self.item1.configure(text='''Item1''')

                self.item1photo = tk.Label(self.item1frame)
                self.item1photo.place(relx=0.063, rely=0.339, height=41, width=114)
                self.item1photo.configure(activebackground="#d9d9d9")
                self.item1photo.configure(activeforeground="black")
                self.item1photo.configure(anchor='w')
                self.item1photo.configure(background="#ffffff")
                self.item1photo.configure(compound='left')
                self.item1photo.configure(disabledforeground="#a3a3a3")
                self.item1photo.configure(foreground="#000000")
                self.item1photo.configure(highlightbackground="#d9d9d9")
                self.item1photo.configure(highlightcolor="#000000")
                self.item1photo.configure(text='''item 1 photo''')

                self.item2frame = tk.Frame(self.eshopframe)
                self.item2frame.place(relx=0.354, rely=0.047, relheight=0.278
                                , relwidth=0.28)
                self.item2frame.configure(relief='groove')
                self.item2frame.configure(borderwidth="2")
                self.item2frame.configure(relief="groove")
                self.item2frame.configure(background="#d9d9d9")
                self.item2frame.configure(highlightbackground="#d9d9d9")
                self.item2frame.configure(highlightcolor="#000000")

                self.item2photo = tk.Label(self.item2frame)
                self.item2photo.place(relx=0.063, rely=0.339, height=41, width=104)
                self.item2photo.configure(activebackground="#d9d9d9")
                self.item2photo.configure(activeforeground="black")
                self.item2photo.configure(anchor='w')
                self.item2photo.configure(background="#ffffff")
                self.item2photo.configure(compound='left')
                self.item2photo.configure(disabledforeground="#a3a3a3")
                self.item2photo.configure(foreground="#000000")
                self.item2photo.configure(highlightbackground="#d9d9d9")
                self.item2photo.configure(highlightcolor="#000000")
                self.item2photo.configure(text='''item 2 photo''')

                self.learnmore2 = tk.Button(self.item2frame)
                self.learnmore2.place(relx=0.063, rely=0.763, height=26, width=137)
                self.learnmore2.configure(activebackground="#d9d9d9")
                self.learnmore2.configure(activeforeground="black")
                self.learnmore2.configure(background="#d9d9d9")
                self.learnmore2.configure(disabledforeground="#a3a3a3")
                self.learnmore2.configure(foreground="#000000")
                self.learnmore2.configure(highlightbackground="#d9d9d9")
                self.learnmore2.configure(highlightcolor="#000000")
                self.learnmore2.configure(text='''Learn more ->''')

                self.item2 = tk.Label(self.item2frame)
                self.item2.place(relx=0.063, rely=0.085, height=21, width=84)
                self.item2.configure(activebackground="#d9d9d9")
                self.item2.configure(activeforeground="black")
                self.item2.configure(anchor='w')
                self.item2.configure(background="#ffffff")
                self.item2.configure(compound='left')
                self.item2.configure(disabledforeground="#a3a3a3")
                self.item2.configure(foreground="#000000")
                self.item2.configure(highlightbackground="#d9d9d9")
                self.item2.configure(highlightcolor="#000000")
                self.item2.configure(text='''item 2''')

                self.addbutton2 = tk.Button(self.item2frame)
                self.addbutton2.place(relx=0.633, rely=0.085, height=26, width=47)
                self.addbutton2.configure(activebackground="#d9d9d9")
                self.addbutton2.configure(activeforeground="black")
                self.addbutton2.configure(background="#0000ff")
                self.addbutton2.configure(disabledforeground="#a3a3a3")
                self.addbutton2.configure(foreground="#ffffff")
                self.addbutton2.configure(highlightbackground="#d9d9d9")
                self.addbutton2.configure(highlightcolor="#000000")
                self.addbutton2.configure(text='''add''')
                self.addbutton2.configure(command=lambda: self.add_item(self.item2))


                self.backbutton = tk.Button(self.eshopframe)
                self.backbutton.place(relx=0.071, rely=0.847, height=36, width=97)
                self.backbutton.configure(activebackground="#d9d9d9")
                self.backbutton.configure(activeforeground="black")
                self.backbutton.configure(background="#0000ff")
                self.backbutton.configure(disabledforeground="#a3a3a3")
                self.backbutton.configure(foreground="#ffffff")
                self.backbutton.configure(highlightbackground="#d9d9d9")
                self.backbutton.configure(highlightcolor="#000000")
                self.backbutton.configure(text='''⟵ BACK''')
                self.backbutton.configure(command=self.go_back)

                self.item3frame = tk.Frame(self.eshopframe)
                self.item3frame.place(relx=0.673, rely=0.047, relheight=0.278
                                , relwidth=0.28)
                self.item3frame.configure(relief='groove')
                self.item3frame.configure(borderwidth="2")
                self.item3frame.configure(relief="groove")
                self.item3frame.configure(background="#d9d9d9")
                self.item3frame.configure(highlightbackground="#d9d9d9")
                self.item3frame.configure(highlightcolor="#000000")

                self.item3 = tk.Label(self.item3frame)
                self.item3.place(relx=0.063, rely=0.085, height=21, width=84)
                self.item3.configure(activebackground="#d9d9d9")
                self.item3.configure(activeforeground="black")
                self.item3.configure(anchor='w')
                self.item3.configure(background="#ffffff")
                self.item3.configure(compound='left')
                self.item3.configure(disabledforeground="#a3a3a3")
                self.item3.configure(foreground="#000000")
                self.item3.configure(highlightbackground="#d9d9d9")
                self.item3.configure(highlightcolor="#000000")
                self.item3.configure(text='''Item 3''')

                self.item3photo = tk.Label(self.item3frame)
                self.item3photo.place(relx=0.063, rely=0.339, height=41, width=104)
                self.item3photo.configure(activebackground="#d9d9d9")
                self.item3photo.configure(activeforeground="black")
                self.item3photo.configure(anchor='w')
                self.item3photo.configure(background="#ffffff")
                self.item3photo.configure(compound='left')
                self.item3photo.configure(disabledforeground="#a3a3a3")
                self.item3photo.configure(foreground="#000000")
                self.item3photo.configure(highlightbackground="#d9d9d9")
                self.item3photo.configure(highlightcolor="#000000")
                self.item3photo.configure(text='''item 3 photo''')

                self.learnmore3 = tk.Button(self.item3frame)
                self.learnmore3.place(relx=0.063, rely=0.763, height=26, width=137)
                self.learnmore3.configure(activebackground="#d9d9d9")
                self.learnmore3.configure(activeforeground="black")
                self.learnmore3.configure(background="#d9d9d9")
                self.learnmore3.configure(disabledforeground="#a3a3a3")
                self.learnmore3.configure(foreground="#000000")
                self.learnmore3.configure(highlightbackground="#d9d9d9")
                self.learnmore3.configure(highlightcolor="#000000")
                self.learnmore3.configure(text='''Learn more ->''')

                self.addbutton3 = tk.Button(self.item3frame)
                self.addbutton3.place(relx=0.633, rely=0.085, height=26, width=47)
                self.addbutton3.configure(activebackground="#d9d9d9")
                self.addbutton3.configure(activeforeground="black")
                self.addbutton3.configure(background="#0000ff")
                self.addbutton3.configure(disabledforeground="#a3a3a3")
                self.addbutton3.configure(foreground="#ffffff")
                self.addbutton3.configure(highlightbackground="#d9d9d9")
                self.addbutton3.configure(highlightcolor="#000000")
                self.addbutton3.configure(text='''add''')
                self.addbutton3.configure(command=lambda: self.add_item(self.item3))


                self.item6frame = tk.Frame(self.eshopframe)
                self.item6frame.place(relx=0.673, rely=0.4, relheight=0.278
                                , relwidth=0.28)
                self.item6frame.configure(relief='groove')
                self.item6frame.configure(borderwidth="2")
                self.item6frame.configure(relief="groove")
                self.item6frame.configure(background="#d9d9d9")
                self.item6frame.configure(highlightbackground="#d9d9d9")
                self.item6frame.configure(highlightcolor="#000000")

                self.item6 = tk.Label(self.item6frame)
                self.item6.place(relx=0.063, rely=0.085, height=21, width=84)
                self.item6.configure(activebackground="#d9d9d9")
                self.item6.configure(activeforeground="black")
                self.item6.configure(anchor='w')
                self.item6.configure(background="#ffffff")
                self.item6.configure(compound='left')
                self.item6.configure(disabledforeground="#a3a3a3")
                self.item6.configure(foreground="#000000")
                self.item6.configure(highlightbackground="#d9d9d9")
                self.item6.configure(highlightcolor="#000000")
                self.item6.configure(text='''item 6''')

                self.item6photo = tk.Label(self.item6frame)
                self.item6photo.place(relx=0.063, rely=0.339, height=41, width=104)
                self.item6photo.configure(activebackground="#d9d9d9")
                self.item6photo.configure(activeforeground="black")
                self.item6photo.configure(anchor='w')
                self.item6photo.configure(background="#ffffff")
                self.item6photo.configure(compound='left')
                self.item6photo.configure(disabledforeground="#a3a3a3")
                self.item6photo.configure(foreground="#000000")
                self.item6photo.configure(highlightbackground="#d9d9d9")
                self.item6photo.configure(highlightcolor="#000000")
                self.item6photo.configure(text='''item 6 photo''')

                self.learnmore6 = tk.Button(self.item6frame)
                self.learnmore6.place(relx=0.063, rely=0.763, height=26, width=137)
                self.learnmore6.configure(activebackground="#d9d9d9")
                self.learnmore6.configure(activeforeground="black")
                self.learnmore6.configure(background="#d9d9d9")
                self.learnmore6.configure(disabledforeground="#a3a3a3")
                self.learnmore6.configure(foreground="#000000")
                self.learnmore6.configure(highlightbackground="#d9d9d9")
                self.learnmore6.configure(highlightcolor="#000000")
                self.learnmore6.configure(text='''Learn more ->''')

                self.addbutton6 = tk.Button(self.item6frame)
                self.addbutton6.place(relx=0.696, rely=0.085, height=26, width=37)
                self.addbutton6.configure(activebackground="#d9d9d9")
                self.addbutton6.configure(activeforeground="black")
                self.addbutton6.configure(background="#0000ff")
                self.addbutton6.configure(disabledforeground="#a3a3a3")
                self.addbutton6.configure(foreground="#ffffff")
                self.addbutton6.configure(highlightbackground="#d9d9d9")
                self.addbutton6.configure(highlightcolor="#000000")
                self.addbutton6.configure(text='''add''')
                self.addbutton6.configure(command=lambda: self.add_item(self.item6))


                self.Button4 = tk.Button(self.eshopframe)
                self.Button4.place(relx=0.354, rely=0.847, height=36, width=107)
                self.Button4.configure(activebackground="#d9d9d9")
                self.Button4.configure(activeforeground="black")
                self.Button4.configure(background="#0000ff")
                self.Button4.configure(disabledforeground="#a3a3a3")
                self.Button4.configure(foreground="#ffffff")
                self.Button4.configure(highlightbackground="#d9d9d9")
                self.Button4.configure(highlightcolor="#000000")
                self.Button4.configure(text='''Payment''', command=self.open_payment_screen)


                self.eshoplist = tk.Listbox(self.eshopframe)
                self.eshoplist.place(relx=0.69, rely=0.729, relheight=0.216
                                , relwidth=0.29)
                self.eshoplist.configure(background="white")
                self.eshoplist.configure(disabledforeground="#a3a3a3")
                self.eshoplist.configure(font="TkFixedFont")
                self.eshoplist.configure(foreground="#000000")
                self.eshoplist.configure(highlightbackground="#d9d9d9")
                self.eshoplist.configure(highlightcolor="#000000")
                self.eshoplist.configure(selectbackground="#d9d9d9")
                self.eshoplist.configure(selectforeground="black")



                #προσθηκη αντικειμένων στο καλάθι

        def add_item(self, item_label):
                item_name = item_label.cget("text")
                self.cart.append(item_name)
                self.eshoplist.insert(tk.END, item_name)
                
        def open_payment_screen(self):
           PaymentScreen.PaymentScreen(tk.Toplevel(self.top))
        
        def go_back(self):
                new_top = tk.Toplevel(self.root)
                new_top.protocol('WM_DELETE_WINDOW', self.root.destroy)
                MainMenuScreen.MainMenuScreen(new_top, self.root, self.username).display(self.top)

        def display(self, previous_window=None):
                if previous_window is not None:
                        previous_window.destroy()
                        self.top.deiconify()

        

if __name__ == '__main__':
       root = tk.Tk()
       root.withdraw()  #Κρύβει το κύριο παράθυρο
       top = tk.Toplevel(root)
       top.protocol('WM_DELETE_WINDOW', root.destroy)
       window = eshopScreen(top, root, username="george_tsavos")
       root.mainloop()
