#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  May 24, 2025 05:17:32 PM EEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 600x450+468+138
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Petato"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "LoginScreen" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra48" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 425 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 295 
    vTcl:DefineAlias "$top.fra48" "AppLogoFrame" vTcl:WidgetProc "LoginScreen" 1
    set site_3_0 $top.fra48
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Rage Italic} -size 36 -weight bold -slant italic" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Petato" 
    vTcl:DefineAlias "$site_3_0.lab49" "AppName" vTcl:WidgetProc "LoginScreen" 1
    label "$site_3_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 
    vTcl:DefineAlias "$site_3_0.lab50" "AppLogo" vTcl:WidgetProc "LoginScreen" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.271 -y 0 -rely 0.024 -width 0 \
        -relwidth 0.488 -height 0 -relheight 0.144 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.034 -y 0 -rely 0.188 -width 0 \
        -relwidth 0.929 -height 0 -relheight 0.779 -anchor nw \
        -bordermode ignore 
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background #ffffff -height 425 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 265 
    vTcl:DefineAlias "$top.fra47" "CredentialsFrame" vTcl:WidgetProc "LoginScreen" 1
    set site_3_0 $top.fra47
    label "$site_3_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #ffffff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Please enter your credentials below." 
    vTcl:DefineAlias "$site_3_0.lab52" "CredentilasLabel" vTcl:WidgetProc "LoginScreen" 1
    entry "$site_3_0.ent54" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 224 
    vTcl:DefineAlias "$site_3_0.ent54" "UsernameEntry" vTcl:WidgetProc "LoginScreen" 1
    label "$site_3_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #ffffff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Password" 
    vTcl:DefineAlias "$site_3_0.lab55" "PasswordLabel" vTcl:WidgetProc "LoginScreen" 1
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #ffffff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Username" 
    vTcl:DefineAlias "$site_3_0.lab53" "UsernameLabel" vTcl:WidgetProc "LoginScreen" 1
    entry "$site_3_0.ent56" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 224 
    vTcl:DefineAlias "$site_3_0.ent56" "PasswordEntry" vTcl:WidgetProc "LoginScreen" 1
    button "$site_3_0.but57" \
        -activebackground #0080ff -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Log-in" 
    vTcl:DefineAlias "$site_3_0.but57" "LoginButton" vTcl:WidgetProc "LoginScreen" 1
    label "$site_3_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #ffffff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 20 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Welcomae Back!" 
    vTcl:DefineAlias "$site_3_0.lab51" "WelocmLabel" vTcl:WidgetProc "LoginScreen" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.165 -width 0 \
        -relwidth 0.808 -height 0 -relheight 0.096 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.376 -width 224 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.471 -width 0 \
        -relwidth 0.242 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.306 -width 0 \
        -relwidth 0.279 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.541 -width 224 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 0 -relx 0.34 -y 0 -rely 0.706 -width 77 -relwidth 0 \
        -height 46 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.024 -width 0 \
        -relwidth 0.921 -height 0 -relheight 0.12 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra48 \
        -in $top -x 0 -relx 0.483 -y 0 -rely 0.022 -width 0 -relwidth 0.492 \
        -height 0 -relheight 0.944 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.442 \
        -height 0 -relheight 0.944 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

