#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  May 16, 2025 09:51:14 AM EEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    image192 "../../../../../../../ProjectLogo.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m48 -background #ffffff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 
    wm focusmodel $top passive
    wm geometry $top 693x474+429+128
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Petato"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "MainMenuScreen" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra49" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 88 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 674 
    vTcl:DefineAlias "$top.fra49" "MenuBarFrame" vTcl:WidgetProc "MainMenuScreen" 1
    set site_3_0 $top.fra49
    button "$site_3_0.but52" \
        -activebackground #0080ff -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Make an Apointment" 
    vTcl:DefineAlias "$site_3_0.but52" "MakeApointmenetButton" vTcl:WidgetProc "MainMenuScreen" 1
    button "$site_3_0.but51" \
        -activebackground #0080ff -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Announcements" 
    vTcl:DefineAlias "$site_3_0.but51" "AnnouncementsButton" vTcl:WidgetProc "MainMenuScreen" 1
    button "$site_3_0.but54" \
        -activebackground #0080ff -activeforeground black -background #ffff00 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "e-shop" 
    vTcl:DefineAlias "$site_3_0.but54" "eshopButton" vTcl:WidgetProc "MainMenuScreen" 1
    button "$site_3_0.but50" \
        -activebackground #0080ff -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "My Profile" 
    vTcl:DefineAlias "$site_3_0.but50" "MyProfileButton" vTcl:WidgetProc "MainMenuScreen" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.527 -y 0 -rely 0.294 -width 137 \
        -relwidth 0 -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.271 -y 0 -rely 0.294 -width 97 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.843 -y 0 -rely 0.294 -width 47 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.294 -anchor nw \
        -bordermode ignore 
    frame "$top.fra48" \
        -relief groove -background #ffffff -height 345 \
        -highlightbackground #ffffff -highlightcolor #000000 -width 674 
    vTcl:DefineAlias "$top.fra48" "AppLogoFrame" vTcl:WidgetProc "MainMenuScreen" 1
    set site_3_0 $top.fra48
    label "$site_3_0.lab49" \
        -activebackground #ffffff -activeforeground #ffffff -anchor w \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #ffffff -font "-family {Segoe UI} -size 9" \
        -foreground #ffffff -highlightbackground #ffffff \
        -highlightcolor #ffffff -image image192 
    vTcl:DefineAlias "$site_3_0.lab49" "AppLogo" vTcl:WidgetProc "MainMenuScreen" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.059 -y 0 -rely 0.087 -width 0 \
        -relwidth 0.88 -height 0 -relheight 0.843 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra49 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.021 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.186 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.232 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.728 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

