#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  May 27, 2025 06:27:52 PM EEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m50 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 600x450+468+138
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Petato"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Make_Search_Announcemnts_Screen" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m50" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background #ffffff -height 405 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 565 
    vTcl:DefineAlias "$top.fra47" "Make_Search_Frame" vTcl:WidgetProc "Make_Search_Announcemnts_Screen" 1
    set site_3_0 $top.fra47
    label "$site_3_0.lab48" \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background #ffffff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 28 -weight bold -underline 1" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Choose an Option:" 
    vTcl:DefineAlias "$site_3_0.lab48" "Make_Search_Label" vTcl:WidgetProc "Make_Search_Announcemnts_Screen" 1
    button "$site_3_0.but51" \
        -activebackground #0080ff -activeforeground black -background #ffffff \
        -borderwidth 4 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Make an Announcemnt" 
    vTcl:DefineAlias "$site_3_0.but51" "Make_Ann_Button" vTcl:WidgetProc "Make_Search_Announcemnts_Screen" 1
    button "$site_3_0.but49" \
        -activebackground #0080ff -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Announcemnts" 
    vTcl:DefineAlias "$site_3_0.but49" "Search_Ann_Button" vTcl:WidgetProc "Make_Search_Announcemnts_Screen" 1
    button "$site_3_0.but52" \
        -activebackground #0080ff -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Back" 
    vTcl:DefineAlias "$site_3_0.but52" "BackButton" vTcl:WidgetProc "Make_Search_Announcemnts_Screen" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.23 -y 0 -rely 0.123 -width 0 \
        -relwidth 0.591 -height 0 -relheight 0.126 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.319 -y 0 -rely 0.321 -width 227 \
        -relwidth 0 -height 46 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.372 -y 0 -rely 0.494 -width 177 \
        -relwidth 0 -height 46 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.442 -y 0 -rely 0.667 -width 97 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.044 -width 0 -relwidth 0.942 \
        -height 0 -relheight 0.9 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

