#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  May 26, 2025 01:58:46 PM EEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m47 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 120x20+230+163
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm grid $top 10 4 6 15
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "MakeAnnouncmentScreen"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "MakeAnnouncmentScreen" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra50" \
        -borderwidth 2 -relief raised -background #ffffff -height 330 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 729 
    vTcl:DefineAlias "$top.fra50" "MakeAnnouncmentScreen" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    set site_3_0 $top.fra50
    ttk::combobox "$site_3_0.tCo49" \
        -values "DOG CAT" -font "-family {Segoe UI} -size 9" \
        -textvariable "combobox" 
    vTcl:DefineAlias "$site_3_0.tCo49" "TCombobox2" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.tCo49
    label "$site_3_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "Title" 
    vTcl:DefineAlias "$site_3_0.lab50" "Label1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab50
    text "$site_3_0.tex47" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 4 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -setgrid 1 \
        -width 10 -wrap word 
    $site_3_0.tex47 configure -font "TkTextFont"
    $site_3_0.tex47 insert end text
    vTcl:DefineAlias "$site_3_0.tex47" "Text1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    ttk::combobox "$site_3_0.tCo48" \
        -values "ADOPTION HOSTING" -font "-family {Segoe UI} -size 9" \
        -textvariable "combobox" 
    vTcl:DefineAlias "$site_3_0.tCo48" "TCombobox1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.tCo48
    text "$site_3_0.tex48" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 4 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -setgrid 1 \
        -width 10 -wrap word 
    $site_3_0.tex48 configure -font "TkTextFont"
    $site_3_0.tex48 insert end text
    vTcl:DefineAlias "$site_3_0.tex48" "Text1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.tex48
    label "$site_3_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "AGE" 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1_1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab51
    text "$site_3_0.tex53" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 4 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -setgrid 1 \
        -width 10 -wrap word 
    $site_3_0.tex53 configure -font "TkTextFont"
    $site_3_0.tex53 insert end text
    vTcl:DefineAlias "$site_3_0.tex53" "Text1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "Gender" 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_2" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab49
    text "$site_3_0.tex49" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 4 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -setgrid 1 \
        -width 10 -wrap word 
    $site_3_0.tex49 configure -font "TkTextFont"
    $site_3_0.tex49 insert end text
    vTcl:DefineAlias "$site_3_0.tex49" "Text1_1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    label "$site_3_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "NAME (IF EXISTS)" 
    vTcl:DefineAlias "$site_3_0.lab52" "Label1_1_2" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab52
    ttk::combobox "$site_3_0.tCo47" \
        -values "MALE FEMALE {}" -font "-family {Segoe UI} -size 9" \
        -textvariable "combobox" 
    vTcl:DefineAlias "$site_3_0.tCo47" "TCombobox3" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.tCo47
    label "$site_3_0.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "TYPE OF ANNOUNCMENT" 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab48
    label "$site_3_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "SPECIES" 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab47
    button "$site_3_0.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #0080ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "CLEAR ALL" 
    vTcl:DefineAlias "$site_3_0.but49" "Button1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.but49
    button "$site_3_0.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #0080ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "BACK" 
    vTcl:DefineAlias "$site_3_0.but50" "Button1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.but50
    button "$site_3_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #0080ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "UPLOAD" 
    vTcl:DefineAlias "$site_3_0.but48" "Button1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.but48
    ttk::combobox "$site_3_0.tCo57" \
        -values "YES NO {} {} {}" -font "-family {Segoe UI} -size 9" \
        -textvariable "combobox" 
    vTcl:DefineAlias "$site_3_0.tCo57" "TCombobox3_2" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.tCo57
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "VACCINATED" 
    vTcl:DefineAlias "$site_3_0.lab56" "Label1_2_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab56
    ttk::combobox "$site_3_0.tCo50" \
        \
        -values "ATHENS,GREECE PATRA,GREECE TRIKALA,GREECE THESALLONIKH,GREECE {} {}" \
        -font "-family {Segoe UI} -size 9" -textvariable "combobox" 
    vTcl:DefineAlias "$site_3_0.tCo50" "TCombobox3_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.tCo50
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "REGION" 
    vTcl:DefineAlias "$site_3_0.lab53" "Label1_1_1_1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab53
    text "$site_3_0.tex56" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 4 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -setgrid 1 \
        -width 10 -wrap word 
    $site_3_0.tex56 configure -font "TkTextFont"
    $site_3_0.tex56 insert end text
    vTcl:DefineAlias "$site_3_0.tex56" "Text1_1_1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "BREED" 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1_1_1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab54
    label "$site_3_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "CONTACT" 
    vTcl:DefineAlias "$site_3_0.lab55" "Label1_2_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab55
    label "$site_3_0.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief groove \
        -text "DATE OF ANNOUNCMENT" 
    vTcl:DefineAlias "$site_3_0.lab58" "Label1_1_3" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    vTcl:copy_lock $site_3_0.lab58
    text "$site_3_0.tex50" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 4 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -setgrid 1 \
        -width 10 -wrap word 
    $site_3_0.tex50 configure -font "TkTextFont"
    $site_3_0.tex50 insert end text
    vTcl:DefineAlias "$site_3_0.tex50" "Text1_1_1_1_1_1" vTcl:WidgetProc "MakeAnnouncmentScreen" 1
    place $site_3_0.tCo49 \
        -in $site_3_0 -x 0 -relx 0.205 -y 0 -rely 0.092 -width 0 \
        -relwidth 0.161 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.21 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex47 \
        -in $site_3_0 -x 0 -relx 0.181 -y 0 -rely 0.214 -width 0 \
        -relwidth 0.182 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo48 \
        -in $site_3_0 -x 0 -relx 0.677 -y 0 -rely 0.093 -width 0 \
        -relwidth 0.234 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex48 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.333 -width 0 \
        -relwidth 0.182 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.333 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex53 \
        -in $site_3_0 -x 0 -relx 0.584 -y 0 -rely 0.333 -width 0 \
        -relwidth 0.169 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.445 -y 0 -rely 0.21 -width 0 \
        -relwidth 0.125 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex49 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.452 -width 0 \
        -relwidth 0.158 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.446 -y 0 -rely 0.333 -width 0 \
        -relwidth 0.135 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo47 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.21 -width 0 \
        -relwidth 0.165 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.444 -y 0 -rely 0.092 -width 0 \
        -relwidth 0.227 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.092 -width 0 \
        -relwidth 0.125 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.458 -y 0 -rely 0.881 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.554 -y 0 -rely 0.881 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.361 -y 0 -rely 0.881 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo57 \
        -in $site_3_0 -x 0 -relx 0.548 -y 0 -rely 0.574 -width 0 \
        -relwidth 0.11 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.446 -y 0 -rely 0.571 -width 0 \
        -relwidth 0.094 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo50 \
        -in $site_3_0 -x 0 -relx 0.548 -y 0 -rely 0.452 -width 0 \
        -relwidth 0.165 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.445 -y 0 -rely 0.452 -width 0 \
        -relwidth 0.094 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex56 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.571 -width 0 \
        -relwidth 0.146 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.452 -width 0 \
        -relwidth 0.094 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.574 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.691 -width 0 \
        -relwidth 0.206 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex50 \
        -in $site_3_0 -x 0 -relx 0.288 -y 0 -rely 0.691 -width 0 \
        -relwidth 0.148 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra50 \
        -in $top -x 0 -relx 0.058 -y 0 -rely 0.091 -width 0 -relwidth 0.848 \
        -height 0 -relheight 0.75 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

